FROM node:20-alpine
RUN npm install -g pnpm@9.0.0
WORKDIR /app
COPY pnpm-workspace.yaml ./
COPY pnpm-lock.yaml ./
COPY package.json ./
COPY apps/web/package.json ./apps/web/
COPY packages/ ./packages/
RUN pnpm install --frozen-lockfile
COPY apps/web ./apps/web
RUN pnpm --filter web build
EXPOSE 3000
ENV NODE_ENV=production
ENV PORT=3000
CMD ["pnpm", "--filter", "web", "start"]
